# Generated by Django 5.1 on 2024-08-29 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_orderplaced_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderplaced',
            name='status',
            field=models.CharField(choices=[('Accepted', 'Accepted'), ('Delivered', 'Delivered'), ('Cancel', 'Cancel'), ('Packed', 'Packed'), ('Pending', 'Pending'), ('On The Way', 'On The Way')], default='pending', max_length=50),
        ),
    ]
